# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindowV1.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1116, 781)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.MainTabMenu = QtWidgets.QTabWidget(self.centralwidget)
        self.MainTabMenu.setGeometry(QtCore.QRect(-4, 39, 1121, 741))
        self.MainTabMenu.setObjectName("MainTabMenu")
        self.HomeTab = QtWidgets.QWidget()
        self.HomeTab.setObjectName("HomeTab")
        self.LastTenLabel = QtWidgets.QLabel(self.HomeTab)
        self.LastTenLabel.setGeometry(QtCore.QRect(50, 20, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.LastTenLabel.setFont(font)
        self.LastTenLabel.setObjectName("LastTenLabel")
        self.LastTenTable = QtWidgets.QTableWidget(self.HomeTab)
        self.LastTenTable.setGeometry(QtCore.QRect(50, 60, 831, 561))
        self.LastTenTable.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.LastTenTable.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.LastTenTable.setColumnCount(1)
        self.LastTenTable.setObjectName("LastTenTable")
        self.LastTenTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.LastTenTable.setHorizontalHeaderItem(0, item)
        self.MainTabMenu.addTab(self.HomeTab, "")
        self.LogViewTab = QtWidgets.QWidget()
        self.LogViewTab.setObjectName("LogViewTab")
        self.MainLogTable = QtWidgets.QTableView(self.LogViewTab)
        self.MainLogTable.setGeometry(QtCore.QRect(50, 60, 831, 561))
        self.MainLogTable.setObjectName("MainLogTable")
        self.LoggedFilmsLabel = QtWidgets.QLabel(self.LogViewTab)
        self.LoggedFilmsLabel.setGeometry(QtCore.QRect(50, 20, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.LoggedFilmsLabel.setFont(font)
        self.LoggedFilmsLabel.setObjectName("LoggedFilmsLabel")
        self.SortByDropdown = QtWidgets.QComboBox(self.LogViewTab)
        self.SortByDropdown.setGeometry(QtCore.QRect(370, 30, 171, 22))
        self.SortByDropdown.setObjectName("SortByDropdown")
        self.SortByDropdown.addItem("")
        self.SortByDropdown.addItem("")
        self.SortByDropdown.addItem("")
        self.SortByDropdown.addItem("")
        self.SortByDropdown.addItem("")
        self.SortByLabel = QtWidgets.QLabel(self.LogViewTab)
        self.SortByLabel.setGeometry(QtCore.QRect(270, 20, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.SortByLabel.setFont(font)
        self.SortByLabel.setObjectName("SortByLabel")
        self.MainTabMenu.addTab(self.LogViewTab, "")
        self.InsightsTab = QtWidgets.QWidget()
        self.InsightsTab.setObjectName("InsightsTab")
        self.InsightsStackedWidget = QtWidgets.QStackedWidget(self.InsightsTab)
        self.InsightsStackedWidget.setGeometry(QtCore.QRect(20, 10, 1061, 681))
        self.InsightsStackedWidget.setObjectName("InsightsStackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.MoviesOverTimePlaceholder = QtWidgets.QWidget(self.page)
        self.MoviesOverTimePlaceholder.setGeometry(QtCore.QRect(60, 10, 911, 621))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.MoviesOverTimePlaceholder.setFont(font)
        self.MoviesOverTimePlaceholder.setAutoFillBackground(False)
        self.MoviesOverTimePlaceholder.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.MoviesOverTimePlaceholder.setObjectName("MoviesOverTimePlaceholder")
        self.MoviesVersusTimeLabel = QtWidgets.QLabel(self.page)
        self.MoviesVersusTimeLabel.setGeometry(QtCore.QRect(60, 640, 101, 16))
        self.MoviesVersusTimeLabel.setObjectName("MoviesVersusTimeLabel")
        self.InsightsStackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.GenrePieChartPlaceholder = QtWidgets.QWidget(self.page_2)
        self.GenrePieChartPlaceholder.setGeometry(QtCore.QRect(120, 80, 831, 541))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.GenrePieChartPlaceholder.setFont(font)
        self.GenrePieChartPlaceholder.setAutoFillBackground(False)
        self.GenrePieChartPlaceholder.setStyleSheet("background-color: rgb(170, 0, 0);")
        self.GenrePieChartPlaceholder.setObjectName("GenrePieChartPlaceholder")
        self.GenrePieChartLabel = QtWidgets.QLabel(self.page_2)
        self.GenrePieChartLabel.setGeometry(QtCore.QRect(130, 630, 101, 31))
        self.GenrePieChartLabel.setObjectName("GenrePieChartLabel")
        self.InsightsStackedWidget.addWidget(self.page_2)
        self.MainTabMenu.addTab(self.InsightsTab, "")
        self.AddMediaButton = QtWidgets.QPushButton(self.centralwidget)
        self.AddMediaButton.setGeometry(QtCore.QRect(1034, 10, 61, 41))
        self.AddMediaButton.setObjectName("AddMediaButton")
        self.SettingsButton = QtWidgets.QPushButton(self.centralwidget)
        self.SettingsButton.setGeometry(QtCore.QRect(970, 10, 61, 41))
        self.SettingsButton.setObjectName("SettingsButton")
        self.CinemaStatsLabel = QtWidgets.QLabel(self.centralwidget)
        self.CinemaStatsLabel.setGeometry(QtCore.QRect(10, 0, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.CinemaStatsLabel.setFont(font)
        self.CinemaStatsLabel.setObjectName("CinemaStatsLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.MainTabMenu.setCurrentIndex(0)
        self.InsightsStackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Cinema Stats V1.0"))
        self.LastTenLabel.setText(_translate("MainWindow", "Last 10 Films"))
        item = self.LastTenTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Test"))
        self.MainTabMenu.setTabText(self.MainTabMenu.indexOf(self.HomeTab), _translate("MainWindow", "Home"))
        self.LoggedFilmsLabel.setText(_translate("MainWindow", "Logged Films"))
        self.SortByDropdown.setItemText(0, _translate("MainWindow", "Date Logged"))
        self.SortByDropdown.setItemText(1, _translate("MainWindow", "Movie Title (Ascending)"))
        self.SortByDropdown.setItemText(2, _translate("MainWindow", "Movie Title (Descending)"))
        self.SortByDropdown.setItemText(3, _translate("MainWindow", "Rating"))
        self.SortByDropdown.setItemText(4, _translate("MainWindow", "Genre"))
        self.SortByLabel.setText(_translate("MainWindow", "Sort By:"))
        self.MainTabMenu.setTabText(self.MainTabMenu.indexOf(self.LogViewTab), _translate("MainWindow", "Log View"))
        self.MoviesVersusTimeLabel.setText(_translate("MainWindow", "Movies Versus Time"))
        self.GenrePieChartLabel.setText(_translate("MainWindow", "Genre Pie Chart"))
        self.MainTabMenu.setTabText(self.MainTabMenu.indexOf(self.InsightsTab), _translate("MainWindow", "Insights"))
        self.AddMediaButton.setText(_translate("MainWindow", "Add Media"))
        self.SettingsButton.setText(_translate("MainWindow", "Settings"))
        self.CinemaStatsLabel.setText(_translate("MainWindow", "Cinema Stats"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
